# Generated by Django 5.2.17 on 2026-09-25 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnloadHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交接时刻')),
                ('receiverTeam', models.CharField(max_length=80, verbose_name='接收班组')),
                ('outputKg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出叶千克')),
                ('signer', models.CharField(max_length=80, verbose_name='签字人')),
                ('completedAt', models.DateTimeField(blank=True, null=True, verbose_name='完成时刻')),
                ('trough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='gardens.trough', verbose_name='所属槽位')),
            ],
            options={
                'verbose_name': '下槽交接卷',
                'verbose_name_plural': '下槽交接卷',
                'ordering': ['-handedAt', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('completedAt__isnull', True)), fields=('trough',), name='uniq_open_handover_per_trough')],
            },
        ),
    ]
